Thu Feb 09 13:00:09 CST 2023 : Servidor de red Apache Derby: Se ha iniciado 10.14.2.0 - (1828579) y está listo para aceptar las conexiones en el puerto 1527
Thu Feb 09 13:33:11 CST 2023 : Servidor de red Apache Derby: Se ha iniciado 10.14.2.0 - (1828579) y está listo para aceptar las conexiones en el puerto 1527
Thu Feb 09 13:33:18 CST 2023 : Número de conexión: 1.
----------------------------------------------------------------
Thu Feb 09 13:33:18 CST 2023:
 Iniciando instancia a816c00e-0186-37aa-e149-ffffdad6a827 de Derby, versión The Apache Software Foundation - Apache Derby - 10.14.2.0 - (1828579): 
en el directorio de base de datos D:\Users\0215391\Documents\Derby_UP\pruebas con el cargador de clases jdk.internal.loader.ClassLoaders$AppClassLoader@2cdf8d8a
Cargado desde file:/D:/Users/0215391/Documents/Derby_UP/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=11.0.17+10-LTS-269
user.dir=D:\Users\0215391\Documents\Derby_UP
os.name=Windows 11
os.arch=amd64
os.version=10.0
derby.system.home=D:\Users\0215391\Documents\Derby_UP
Cargador de clases de base de datos iniciado - derby.database.classpath=''
Thu Feb 09 13:33:22 CST 2023 Thread[DRDAConnThread_2,5,main] (DATABASE = pruebas), (DRDAID = {1}), Apache Derby Network Server connected to database pruebas;create=true
Thu Feb 09 13:34:39 CST 2023 : Número de conexión: 2.
Thu Feb 09 13:34:39 CST 2023 Thread[DRDAConnThread_3,5,main] (DATABASE = pruebas), (DRDAID = {2}), Apache Derby Network Server connected to database pruebas;create=true
Thu Feb 09 13:36:11 CST 2023 : Número de conexión: 3.
Thu Feb 09 13:36:11 CST 2023 Thread[DRDAConnThread_3,5,main] (DATABASE = pruebas), (DRDAID = {3}), Apache Derby Network Server connected to database pruebas;create=true
Thu Feb 09 14:04:11 CST 2023 : Número de conexión: 4.
Thu Feb 09 14:04:11 CST 2023 Thread[DRDAConnThread_2,5,main] (DATABASE = pruebas), (DRDAID = {4}), Apache Derby Network Server connected to database pruebas;create=true
Thu Feb 09 14:05:04 CST 2023 : Servidor de red Apache Derby: Se ha iniciado 10.14.2.0 - (1828579) y está listo para aceptar las conexiones en el puerto 1527
Thu Feb 09 14:05:16 CST 2023 : Número de conexión: 1.
----------------------------------------------------------------
Thu Feb 09 14:05:16 CST 2023:
 Iniciando instancia a816c00e-0186-37c8-14b5-ffffdad6a827 de Derby, versión The Apache Software Foundation - Apache Derby - 10.14.2.0 - (1828579): 
en el directorio de base de datos D:\Users\0215391\Documents\Derby_UP\pruebas con el cargador de clases jdk.internal.loader.ClassLoaders$AppClassLoader@2cdf8d8a
Cargado desde file:/D:/Users/0215391/Documents/Derby_UP/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=11.0.17+10-LTS-269
user.dir=D:\Users\0215391\Documents\Derby_UP
os.name=Windows 11
os.arch=amd64
os.version=10.0
derby.system.home=D:\Users\0215391\Documents\Derby_UP
Cargador de clases de base de datos iniciado - derby.database.classpath=''
Thu Feb 09 14:05:17 CST 2023 Thread[DRDAConnThread_2,5,main] (DATABASE = pruebas), (DRDAID = {1}), Apache Derby Network Server connected to database pruebas;create=true
Thu Feb 09 14:16:56 CST 2023 : Servidor de red Apache Derby: Se ha iniciado 10.14.2.0 - (1828579) y está listo para aceptar las conexiones en el puerto 1527
Thu Feb 09 14:17:04 CST 2023 : Número de conexión: 1.
----------------------------------------------------------------
Thu Feb 09 14:17:04 CST 2023:
 Iniciando instancia a816c00e-0186-37d2-eec1-ffffdad6a827 de Derby, versión The Apache Software Foundation - Apache Derby - 10.14.2.0 - (1828579): 
en el directorio de base de datos D:\Users\0215391\Documents\Derby_UP\pruebas con el cargador de clases jdk.internal.loader.ClassLoaders$AppClassLoader@2cdf8d8a
Cargado desde file:/D:/Users/0215391/Documents/Derby_UP/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=11.0.17+10-LTS-269
user.dir=D:\Users\0215391\Documents\Derby_UP
os.name=Windows 11
os.arch=amd64
os.version=10.0
derby.system.home=D:\Users\0215391\Documents\Derby_UP
Cargador de clases de base de datos iniciado - derby.database.classpath=''
Thu Feb 09 14:17:05 CST 2023 Thread[DRDAConnThread_2,5,main] (DATABASE = pruebas), (DRDAID = {1}), Apache Derby Network Server connected to database pruebas;create=true
Thu Feb 09 14:17:17 CST 2023 : Número de conexión: 2.
Thu Feb 09 14:17:17 CST 2023 Thread[DRDAConnThread_2,5,main] (XID = 266), (SESSIONID = 2), (DATABASE = pruebas), (DRDAID = {2}), Cleanup action starting
java.sql.SQLNonTransientConnectionException: Se ha producido un fallo de autenticación de conexión. Motivo: Autenticación no válida..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR 08004: Se ha producido un fallo de autenticación de conexión. Motivo: Autenticación no válida..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 21 more
============= begin nested exception, level (1) ===========
ERROR 08004: Se ha producido un fallo de autenticación de conexión. Motivo: Autenticación no válida..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Thu Feb 09 14:17:17 CST 2023 Thread[DRDAConnThread_2,5,main] (DATABASE = pruebas), (DRDAID = {2}), Se ha producido un fallo de autenticación de conexión. Motivo: Autenticación no válida..
Thu Feb 09 14:17:24 CST 2023 : Número de conexión: 3.
Thu Feb 09 14:17:24 CST 2023 Thread[DRDAConnThread_2,5,main] (XID = 267), (SESSIONID = 3), (DATABASE = pruebas), (DRDAID = {3}), Cleanup action starting
java.sql.SQLNonTransientConnectionException: Se ha producido un fallo de autenticación de conexión. Motivo: Autenticación no válida..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR 08004: Se ha producido un fallo de autenticación de conexión. Motivo: Autenticación no válida..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 21 more
============= begin nested exception, level (1) ===========
ERROR 08004: Se ha producido un fallo de autenticación de conexión. Motivo: Autenticación no válida..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Thu Feb 09 14:17:24 CST 2023 Thread[DRDAConnThread_2,5,main] (DATABASE = pruebas), (DRDAID = {3}), Se ha producido un fallo de autenticación de conexión. Motivo: Autenticación no válida..
Thu Feb 09 14:17:30 CST 2023 : Número de conexión: 4.
Thu Feb 09 14:17:30 CST 2023 Thread[DRDAConnThread_2,5,main] (DATABASE = pruebas), (DRDAID = {4}), Apache Derby Network Server connected to database pruebas;create=true
